# Generated by Django 3.1.2 on 2020-10-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Attributes',
        ),
        migrations.RenameModel(
            old_name='BodyColor',
            new_name='BodyColors',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Colors',
        ),
        migrations.RenameModel(
            old_name='Field',
            new_name='Fields',
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
        migrations.RenameModel(
            old_name='InkColor',
            new_name='InkColors',
        ),
        migrations.RenameModel(
            old_name='ProdcutImage',
            new_name='ProdcutImages',
        ),
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProductAttributes',
        ),
        migrations.RenameModel(
            old_name='ProductOption',
            new_name='ProductOptions',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='ProductThickness',
            new_name='ProductThicknesses',
        ),
        migrations.RenameModel(
            old_name='Thickness',
            new_name='Thicknesses',
        ),
    ]
