<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-22 02:19
=======
# Generated by Django 3.1.2 on 2020-10-22 11:35
>>>>>>> 6ca094c1872151b899b0ae0b1cc92220ca22d831

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='000000', max_length=45),
        ),
    ]
