# Generated by Django 3.1.2 on 2020-10-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201021_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductThicknesses',
            new_name='ProductThickness',
        ),
    ]
