# Generated by Django 3.1.2 on 2020-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201020_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gift',
            field=models.BooleanField(null=True),
        ),
    ]
