# Generated by Django 3.1.2 on 2020-10-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201020_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('origin', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('create_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('sales_amount', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('plus_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_options',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_tags',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Fields',
            new_name='Field',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productoptions',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='group',
        ),
        migrations.RenameField(
            model_name='productthicknesses',
            old_name='color',
            new_name='thickness',
        ),
        migrations.RenameField(
            model_name='thickness',
            old_name='thickness',
            new_name='value',
        ),
        migrations.AlterModelTable(
            name='productthicknesses',
            table='product_thicknesses',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
        migrations.RenameModel(
            old_name='BodyColors',
            new_name='BodyColor',
        ),
        migrations.RenameModel(
            old_name='InkColors',
            new_name='InkColor',
        ),
        migrations.RenameModel(
            old_name='ProdcutImages',
            new_name='ProductImage',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Subcategory',
        ),
        migrations.RenameModel(
            old_name='Thicknesses',
            new_name='Thickness',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.DeleteModel(
            name='ProductOptions',
        ),
        migrations.AddField(
            model_name='producttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tag'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='body_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bodycolor'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='ink_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.inkcolor'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.thickness'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='bodycolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AlterField(
            model_name='bodycolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='inkcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AlterField(
            model_name='inkcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productthicknesses',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
