# Generated by Django 3.1.2 on 2020-10-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=45)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('sms_agreement', models.BooleanField()),
                ('email_agreement', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
