# Generated by Django 3.1.2 on 2020-10-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
