# Generated by Django 3.1.2 on 2020-10-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201027_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='아파트', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='010-1234-5678', max_length=50),
        ),
    ]
