# Generated by Django 3.1.2 on 2020-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_ammount',
            new_name='product_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_number',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
