# Generated by Django 3.1.2 on 2020-10-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201021_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
