# Generated by Django 3.1.2 on 2020-10-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201022_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_ammount',
            new_name='product_amount',
        ),
    ]
