# Generated by Django 3.1.2 on 2020-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201022_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
