# Generated by Django 3.1.2 on 2020-10-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201023_0738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productreview',
            table=None,
        ),
    ]
