# Generated by Django 3.1.2 on 2020-10-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201025_0527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productreview',
            table='product_reviews',
        ),
    ]
